import type { Metadata } from "next";
import { Ultra } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'
import localFont from '@next/font/local';
export const ultra = Ultra({ subsets: ["latin"],
  weight: '400',
 });

 export const myFont = localFont({src: './dream.ttf'})

const roboto = Roboto({ subsets: ["latin"],
      weight:'400'
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='bg-brown text-white'>
      <body className={myFont.className}>{children}</body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
